/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mohammed.hani;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author dell
 */
public class ATM extends javax.swing.JFrame {
    BufferedReader bufferedReader, bufferedReaderUpdate;
    FileOutputStream fileOutputStream;
    boolean flag = false;
    public static String balance;
    public static String wantedLine;
    boolean depoFlag = false;

    /**
     * Creates new form ATM
     */
    public ATM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mainText = new javax.swing.JTextPane();
        button10 = new javax.swing.JButton();
        label10 = new javax.swing.JLabel();
        button100 = new javax.swing.JButton();
        label100 = new javax.swing.JLabel();
        button200 = new javax.swing.JButton();
        label200 = new javax.swing.JLabel();
        button400 = new javax.swing.JButton();
        label400 = new javax.swing.JLabel();
        buttonOther = new javax.swing.JButton();
        labelOther = new javax.swing.JLabel();
        button20 = new javax.swing.JButton();
        label20 = new javax.swing.JLabel();
        button40 = new javax.swing.JButton();
        label40 = new javax.swing.JLabel();
        button60 = new javax.swing.JButton();
        label60 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        number7 = new javax.swing.JButton();
        number8 = new javax.swing.JButton();
        number9 = new javax.swing.JButton();
        number4 = new javax.swing.JButton();
        number5 = new javax.swing.JButton();
        number6 = new javax.swing.JButton();
        number1 = new javax.swing.JButton();
        number2 = new javax.swing.JButton();
        number3 = new javax.swing.JButton();
        number0 = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        buttonInsert = new javax.swing.JButton();
        buttonOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainText.setEnabled(false);
        jScrollPane1.setViewportView(mainText);

        button10.setText(">");
        button10.setEnabled(false);
        button10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button10ActionPerformed(evt);
            }
        });

        button100.setText("<");
        button100.setEnabled(false);
        button100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button100ActionPerformed(evt);
            }
        });

        label100.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        button200.setText("<");
        button200.setEnabled(false);
        button200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button200ActionPerformed(evt);
            }
        });

        label200.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        button400.setText("<");
        button400.setEnabled(false);
        button400.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button400ActionPerformed(evt);
            }
        });

        label400.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        buttonOther.setText("<");
        buttonOther.setEnabled(false);
        buttonOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOtherActionPerformed(evt);
            }
        });

        labelOther.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        button20.setText(">");
        button20.setEnabled(false);
        button20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button20ActionPerformed(evt);
            }
        });

        button40.setText(">");
        button40.setEnabled(false);
        button40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button40ActionPerformed(evt);
            }
        });

        button60.setText(">");
        button60.setEnabled(false);
        button60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button60ActionPerformed(evt);
            }
        });

        password.setEnabled(false);
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        number7.setText("7");
        number7.setEnabled(false);
        number7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number7ActionPerformed(evt);
            }
        });

        number8.setText("8");
        number8.setEnabled(false);
        number8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number8ActionPerformed(evt);
            }
        });

        number9.setText("9");
        number9.setEnabled(false);
        number9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number9ActionPerformed(evt);
            }
        });

        number4.setText("4");
        number4.setEnabled(false);
        number4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number4ActionPerformed(evt);
            }
        });

        number5.setText("5");
        number5.setEnabled(false);
        number5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number5ActionPerformed(evt);
            }
        });

        number6.setText("6");
        number6.setEnabled(false);
        number6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number6ActionPerformed(evt);
            }
        });

        number1.setText("1");
        number1.setEnabled(false);
        number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number1ActionPerformed(evt);
            }
        });

        number2.setText("2");
        number2.setEnabled(false);
        number2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number2ActionPerformed(evt);
            }
        });

        number3.setText("3");
        number3.setEnabled(false);
        number3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number3ActionPerformed(evt);
            }
        });

        number0.setText("0");
        number0.setEnabled(false);
        number0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number0ActionPerformed(evt);
            }
        });

        buttonCancel.setBackground(new java.awt.Color(255, 0, 0));
        buttonCancel.setText("✕");
        buttonCancel.setEnabled(false);
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        buttonInsert.setBackground(new java.awt.Color(255, 255, 102));
        buttonInsert.setText("−");
        buttonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertActionPerformed(evt);
            }
        });

        buttonOk.setBackground(new java.awt.Color(102, 255, 51));
        buttonOk.setText("✓");
        buttonOk.setEnabled(false);
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(button10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(button20, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(button40, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label40, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(button60, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label60, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(password)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label100, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button100, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label200, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button200, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label400, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button400, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(buttonInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(labelOther, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonOther, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(number4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(number5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(number6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(number7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(number8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(number9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(number0, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(number3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button10)
                            .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button20)
                            .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button40)
                            .addComponent(label40, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button60)
                            .addComponent(label60, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button100)
                            .addComponent(label100, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button200)
                            .addComponent(label200, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button400)
                            .addComponent(label400, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonOther)
                            .addComponent(labelOther, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(number7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(number8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(number9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(number4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(number5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(number6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(number3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(number0, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // main amounts buttons.................................................................................................
    
    private void button10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button10ActionPerformed
        checkAmount(10);
    }//GEN-LAST:event_button10ActionPerformed

    private void button20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button20ActionPerformed
        checkAmount(20);
    }//GEN-LAST:event_button20ActionPerformed

    private void button40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button40ActionPerformed
        checkAmount(40);
    }//GEN-LAST:event_button40ActionPerformed

    private void button60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button60ActionPerformed
        checkAmount(60);
    }//GEN-LAST:event_button60ActionPerformed

    private void button100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button100ActionPerformed
        checkAmount(100);
    }//GEN-LAST:event_button100ActionPerformed

    private void button200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button200ActionPerformed
        if (!label200.getText().equals("200")){
            flag = true;
            checkPasswordAndMoney("");
        }else{
            checkAmount(200);
        }
        
    }//GEN-LAST:event_button200ActionPerformed

    private void button400ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button400ActionPerformed
        if (label400.getText().equals("deposite")){
            flag = true;
            depoFlag = true;
            setNumberButtonsEnabled(true);
            mainText.setText("Enter the money:");
            setMainButtonsEnabled(true);
            return;
        }
        checkAmount(400);
    }//GEN-LAST:event_button400ActionPerformed

    private void buttonOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOtherActionPerformed
        if (labelOther.getText().equals("check")){
            mainText.setText("your balance is:"+balance);
            return;
        }
        setNumberButtonsEnabled(true);
        mainText.setText("Enter the Amount:");
        flag = true;
        setMainButtonsEnabled(true);
    }//GEN-LAST:event_buttonOtherActionPerformed

    // 0-9 buttons.................................................................................................
    
    private void number0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number0ActionPerformed
        checkPasswordAndMoney("0");
    }//GEN-LAST:event_number0ActionPerformed

    private void number1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number1ActionPerformed
        checkPasswordAndMoney("1");
    }//GEN-LAST:event_number1ActionPerformed

    private void number2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number2ActionPerformed
        checkPasswordAndMoney("2");
    }//GEN-LAST:event_number2ActionPerformed

    private void number3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number3ActionPerformed
        checkPasswordAndMoney("3");
    }//GEN-LAST:event_number3ActionPerformed

    private void number4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number4ActionPerformed
        checkPasswordAndMoney("4");
    }//GEN-LAST:event_number4ActionPerformed

    private void number5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number5ActionPerformed
        checkPasswordAndMoney("5");
    }//GEN-LAST:event_number5ActionPerformed

    private void number6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number6ActionPerformed
        checkPasswordAndMoney("6");
    }//GEN-LAST:event_number6ActionPerformed

    private void number7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number7ActionPerformed
        checkPasswordAndMoney("7");
    }//GEN-LAST:event_number7ActionPerformed

    private void number8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number8ActionPerformed
        checkPasswordAndMoney("8");
    }//GEN-LAST:event_number8ActionPerformed

    private void number9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number9ActionPerformed
        checkPasswordAndMoney("9");
    }//GEN-LAST:event_number9ActionPerformed

    // main three button.................................................................................................
    
    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
        if (depoFlag == true){
            int indx = mainText.getText().lastIndexOf(":")+1;
            String str = mainText.getText().substring(indx);
            int depo = Integer.parseInt(str);
            if (depo >= 10){
                int bal = Integer.parseInt(balance);
                updateBalance(bal + depo);
                mainText.setText("deposited is done");
            }else{
                mainText.setText("deposite Amount must be equal or more than 10");
            }
            return;
        }
        int index = mainText.getText().lastIndexOf(":")+1;
        String str = mainText.getText().substring(index);
        int num = Integer.parseInt(str);
        checkAmount(num);
        
    }//GEN-LAST:event_buttonOkActionPerformed

    private void buttonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertActionPerformed
        flag = false;
        depoFlag = false;
        password.setText("");
        mainText.setText("");
        emptyLabel();
        setNumberButtonsEnabled(true);
        setMoneyButtonsEnabled(false);
    }//GEN-LAST:event_buttonInsertActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        emptyLabel();
        emptyMainService();
        setNumberButtonsEnabled(false);
        setMainServiceButtonsEnabled(false);
        setMoneyButtonsEnabled(false);
        setMainButtonsEnabled(false);
        mainText.setText("");
        password.setText("");
        
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    // my methods.................................................................................................
    
    public void setMainAmount(){
        label10.setText("10");
        label20.setText("20");
        label40.setText("40");
        label60.setText("60");
        label100.setText("100");
        label200.setText("200");
        label400.setText("400");
        labelOther.setText("other");
    }
    
    public void emptyLabel(){
        label10.setText("");
        label20.setText("");
        label40.setText("");
        label60.setText("");
        label100.setText("");
        label200.setText("");
        label400.setText("");
        labelOther.setText("");
    }
    
    public void setMainService(){
        label200.setText("withdraw");
        label400.setText("deposite");
        labelOther.setText("check");
    }
    
    public void emptyMainService(){
        label200.setText("");
        label400.setText("");
        labelOther.setText("");
    }
    
    public void setNumberButtonsEnabled(boolean enabled){
        if (enabled == true){
            number0.setEnabled(true);
            number1.setEnabled(true);
            number2.setEnabled(true);
            number3.setEnabled(true);
            number4.setEnabled(true);
            number5.setEnabled(true);
            number6.setEnabled(true);
            number7.setEnabled(true);
            number8.setEnabled(true);
            number9.setEnabled(true);
        }else{
            number0.setEnabled(false);
            number1.setEnabled(false);
            number2.setEnabled(false);
            number3.setEnabled(false);
            number4.setEnabled(false);
            number5.setEnabled(false);
            number6.setEnabled(false);
            number7.setEnabled(false);
            number8.setEnabled(false);
            number9.setEnabled(false);
        }        
        
    }
    
    public void setMainServiceButtonsEnabled(boolean enabled){
        if (enabled){
            button200.setEnabled(true);
            button400.setEnabled(true);
            buttonOther.setEnabled(true);
        }else{
            button200.setEnabled(false);
            button400.setEnabled(false);
            buttonOther.setEnabled(false);
        }
    }
    
    public void setMoneyButtonsEnabled(boolean enabled){
        if (enabled){
            button10.setEnabled(true);
            button20.setEnabled(true);
            button40.setEnabled(true);
            button60.setEnabled(true);
            button100.setEnabled(true);
            button200.setEnabled(true);
            button400.setEnabled(true);
            buttonOther.setEnabled(true);
        }else{
            button10.setEnabled(false);
            button20.setEnabled(false);
            button40.setEnabled(false);
            button60.setEnabled(false);
            button100.setEnabled(false);
            button200.setEnabled(false);
            button400.setEnabled(false);
            buttonOther.setEnabled(false);
        }
        
    }
    
    public void setMainButtonsEnabled(boolean enabled){
        if(enabled){
            buttonOk.setEnabled(true);
            buttonCancel.setEnabled(true);
        }else{
            buttonOk.setEnabled(false);
            buttonCancel.setEnabled(false);
        }
    }
    
    // my algorithm.............................................................................................
    
    public void checkPasswordAndMoney(String num){
        if (flag == false){//for password
            password.setText(password.getText()+num);
            if (password.getText().length() == 3){
                setNumberButtonsEnabled(false);
                checkPassword();
            }
        }else if(depoFlag == true){
            mainText.setText(mainText.getText()+num);
            return;
        }else {//for withdraw
            if (label200.getText().equals("withdraw")){
                setMainAmount();
                setMoneyButtonsEnabled(true);
            }
            mainText.setText(mainText.getText()+num);
        }
    }
    
    public void checkPassword(){
        try {
            bufferedReader = new BufferedReader(new FileReader("Clients Accounts.txt"));
            String line;
            while ((line = bufferedReader.readLine()) != null){
                if (line.contains(" "+password.getText()+" ")){
                    int index = line.lastIndexOf(" ")+1;
                    balance = line.substring(index);
                    setMainService();
                    setMainServiceButtonsEnabled(true);
                    wantedLine = line;

                    break;
                }
            }
            if ((line = bufferedReader.readLine()+1) == null){
                mainText.setText("incorrect password");

            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ATM.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ATM.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void checkAmount(int num){
        int bal = Integer.parseInt(balance);
        if (num > bal){
            mainText.setText("your balance is not enoph");
        }else if(num % 10 != 0){
            mainText.setText("the amount must be multiple 10");
        }else if(num > 1000){
            mainText.setText("the amount must be equal or less than 1000");
        }else{
            mainText.setText("withdraw is done please take your card");
            updateBalance(bal - num);
            
        }
    }
    
    public void updateBalance(int num){
        StringBuffer stringBuffer = new StringBuffer();
        String str1, str2, newLine, subStr;
        int indx1, indx2;
        try {
            bufferedReaderUpdate = new BufferedReader(new FileReader("Clients Accounts.txt"));
            String line;
            while ((line = bufferedReaderUpdate.readLine()) != null){
                stringBuffer.append(line);
                stringBuffer.append("\r\n");
            }
            bufferedReaderUpdate.close();
            str1 = stringBuffer.toString();
            
            indx1 = wantedLine.lastIndexOf(" ")+1;
            subStr = wantedLine.substring(indx1);
            newLine = wantedLine.replaceAll(subStr, String.valueOf(num));
            str2 = str1.replaceAll(wantedLine, newLine);
            
            
            fileOutputStream = new FileOutputStream("Clients Accounts.txt");
            fileOutputStream.write(str2.getBytes());
            fileOutputStream.close();
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ATM.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ATM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ATM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button10;
    private javax.swing.JButton button100;
    private javax.swing.JButton button20;
    private javax.swing.JButton button200;
    private javax.swing.JButton button40;
    private javax.swing.JButton button400;
    private javax.swing.JButton button60;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonInsert;
    private javax.swing.JButton buttonOk;
    private javax.swing.JButton buttonOther;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label100;
    private javax.swing.JLabel label20;
    private javax.swing.JLabel label200;
    private javax.swing.JLabel label40;
    private javax.swing.JLabel label400;
    private javax.swing.JLabel label60;
    private javax.swing.JLabel labelOther;
    private javax.swing.JTextPane mainText;
    private javax.swing.JButton number0;
    private javax.swing.JButton number1;
    private javax.swing.JButton number2;
    private javax.swing.JButton number3;
    private javax.swing.JButton number4;
    private javax.swing.JButton number5;
    private javax.swing.JButton number6;
    private javax.swing.JButton number7;
    private javax.swing.JButton number8;
    private javax.swing.JButton number9;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
